CC=clang++
OBJ=main.o

mousesense: main.cpp
	$(CC) -Wall -std=c++17 main.cpp /Users/wgillis/dev/lab/librealsense/build/Debug/librealsense2.2.10.3.dylib -o mousesense -I/Users/wgillis/dev/lab/librealsense/include -L/usr/local/lib -I/Users/wgillis/dev/lab/librealsense/src -I/usr/local/include -L/Users/wgillis/dev/lab/librealsense/build/Debug -I/Users/wgillis/dev/lab/librealsense/realsense2 -L/usr/local/Cellar/libusb/1.0.22/lib -I/usr/local/Cellar/libusb/1.0.22/include/libusb-1.0
